# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jason M. Lewis
email: jason.lewis@fkem1.lu.se
description: >- # this means to ignore newlines until "baseurl:"
  Personal Website of Jason M. Lewis, Researcher in Statistical/Computational Physics & Machine Learning
twitter_username: __jasonlewis
github_username: jasonmlewis
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
#paginate: 0 # amount of posts to show
#paginate_path: /page:num/
timezone: GB # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - .well-known  # bluesky verification

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jason M. Lewis"
  avatar : "assets/images/photo-JasonLewis-website.jpg"
  bio    : "Researcher &#124; Statistical/Computational Physics & Machine Learning"
  links:
    - label: "Email (preferred)"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jason.lewis@fkem1.lu.se"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jason-m-lewis0"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=Ua-ZCwYAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonmlewis"
    - label : "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/jasonmlewis.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/__jasonlewis"
    - label: "Me @ Warwick"
      icon: "fas fa-fw fa-link"
      url: "https://warwick.ac.uk/fac/cross_fac/complexity/people/students/dtc/students2013/lewis/"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jason.lewis@fkem1.lu.se"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jason-m-lewis0"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=Ua-ZCwYAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jasonmlewis"
    - label : "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/jasonmlewis.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/__jasonlewis"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
